pipeline {
    agent {
        label 'agent-nodes'
    }
    stages
    {
        stage('checkout')
        {
            steps{
                git (
                    branch: 'branch4', 
                    url: 'https://github.com/ajaycentos/gke_jenkins_argocd.git'
                )

            }
        }
        stage('Build Docker image')
        {
            steps
            {
                script{
                    dockerImage=docker.build("ajaycentos/myapp:${env.BUILD_ID}","node_app1")
                }
            }
        }

    }
}