pipeline {
  agent {
        label 'agent-nodes'
    }
  stages 
  {
    stage('Docker Build') 
    {
      agent {
		label 'agent-nodes'
	    }
      steps {
            checkout scm
            sh 'cd node_app1'
            sh 'ls -l'
            sh 'docker build -t ajay/sampleapp:v1 -f nodes_app1/Dockerfile .'
            }
    }
  }
}
