pipeline
{
    agent
    {
        
        docker
        {
            label 'agent-nodes'
            image 'node:16-alpine'
        }
    }
    stages
    {
        stage('Test')
        {
            steps
            {
                sh 'node --version'
            }
        }
    }
}